// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgKEiOmBT0CsgK8tRCgfi6isneCpOMVfQ',
    appId: '1:25190735008:web:456abe23a47fdd45e6bdc5',
    messagingSenderId: '25190735008',
    projectId: 'hvt-edusuite',
    authDomain: 'hvt-edusuite.firebaseapp.com',
    storageBucket: 'hvt-edusuite.firebasestorage.app',
    measurementId: 'G-9JHMZ3J56Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzW2KXaRtoAszSd-0rzQfCwkCjB1A8MVk',
    appId: '1:25190735008:android:968b7073f179412ae6bdc5',
    messagingSenderId: '25190735008',
    projectId: 'hvt-edusuite',
    storageBucket: 'hvt-edusuite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCipjBqsxAn0vMQPw3Sn51SMHHdaLAWHo0',
    appId: '1:25190735008:ios:14668094b9b9aff9e6bdc5',
    messagingSenderId: '25190735008',
    projectId: 'hvt-edusuite',
    storageBucket: 'hvt-edusuite.firebasestorage.app',
    iosBundleId: 'com.hvt.esm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCipjBqsxAn0vMQPw3Sn51SMHHdaLAWHo0',
    appId: '1:25190735008:ios:14668094b9b9aff9e6bdc5',
    messagingSenderId: '25190735008',
    projectId: 'hvt-edusuite',
    storageBucket: 'hvt-edusuite.firebasestorage.app',
    iosBundleId: 'com.hvt.esm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgKEiOmBT0CsgK8tRCgfi6isneCpOMVfQ',
    appId: '1:25190735008:web:07ae6980b32de336e6bdc5',
    messagingSenderId: '25190735008',
    projectId: 'hvt-edusuite',
    authDomain: 'hvt-edusuite.firebaseapp.com',
    storageBucket: 'hvt-edusuite.firebasestorage.app',
    measurementId: 'G-WX1L66FHHL',
  );
}
